backup and restore version1

diff --git a/backupNrestore/restore b/backupNrestore/restore
--- a/backupNrestore/restore
+++ b/backupNrestore/restore
@@ -14,57 +14,115 @@ function get_current_dir()
     CURRENT_DIR=`pwd -P`
 }
 
+function create_db_if_not_exist(){
+    DB_NAME=$1
+    echo "Creating DB if not exist ( $DB_NAME )"
+
+    if [[ -z $MYSQL_ADMIN_USERNAME ]]; then
+        echo "[ error ] You don't have permission to create DB, Manually create DB using phpMyAdmin and try again"
+        exit 1
+    fi
+
+    mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" 2>/dev/null 1>/dev/null 
+}
+
+function create_db_user_if_not_exist(){
+    DB_NAME=$1
+    DB_USER=$2
+    DB_PASS=$3
+
+    echo "Creating DB USER if not exist ( $DB_USER )"
+
+    if [[ -z $MYSQL_ADMIN_USERNAME ]]; then
+        echo "[ error ] You don't have permission to create DB, Manually create DB using phpMyAdmin and try again"
+        exit 1
+    fi
+
+    mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT -e "CREATE USER '$DB_USER'@'$DB_HOST' IDENTIFIED BY '$DB_PASS';" 2>/dev/null 1>/dev/null
+
+    echo "update db password"
+    mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT -e "SET PASSWORD FOR '$DB_USER'@'$DB_HOST' = PASSWORD('$DB_PASS');" 2>/dev/null 1>/dev/null
+    
+    echo "grand db privileges"
+    mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '$DB_USER'@'$DB_HOST';" 2>/dev/null 1>/dev/null
+    #mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '$DB_USER'@'$DB_HOST' WITH GRANT OPTION;" 2>/dev/null 1>/dev/null
+    #mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT $DB_NAME -e "GRANT ALL PRIVILEGES TO '$DB_USER'@'$DB_HOST';" 2>/dev/null 1>/dev/null
+    #mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT -e "GRANT ALL PRIVILEGES ON *.* TO '$DB_USER'@'$DB_HOST';" 2>/dev/null 1>/dev/null
+    #mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT -e "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON ${DB_NAME}.* TO '$DB_USER'@'$DB_HOST';" 2>/dev/null 1>/dev/null
+}
+
 function is_db_empty()
 {
     DB_NAME=$1
     DB_USER=$2
     DB_PASS=$3
+    CMD_STATUS=1
 
     if [[ -z $MYSQL_ADMIN_USERNAME ]]; then
-        table_count=$(mysql -u$DB_USER -p$DB_PASS -h $DB_HOST -P $DB_PORT $DB_NAME -e "SHOW TABLES;" | wc -l)
+        table_count=$(mysql -u$DB_USER -p$DB_PASS -h $DB_HOST -P $DB_PORT $DB_NAME -e "SHOW TABLES;" 2> /dev/null | wc -l)
+        mysql -u$DB_USER -p$DB_PASS -h $DB_HOST -P $DB_PORT $DB_NAME -e "SHOW TABLES;" 1> /dev/null 2> /dev/null
+        CMD_STATUS=$?
     else
-        table_count=$(mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT $DB_NAME -e "SHOW TABLES;" | wc -l)
+        table_count=$(mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT $DB_NAME -e "SHOW TABLES;" 2> /dev/null | wc -l)
+        mysql -u$MYSQL_ADMIN_USERNAME -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT $DB_NAME -e "SHOW TABLES;" 1> /dev/null 2> /dev/null
+        CMD_STATUS=$?
     fi
 
-    if [ $table_count -gt 0 ];then
-        echo "  [ ERROR ] [ ${LINENO} ] DB is not empty ( table_count : $table_count ), truncate database before restore"
-        echo
-        echo "     -> $DB_NAME"
-        echo
-        echo
-        exit 1
+    if [ $CMD_STATUS -ne 0 ]; then
+        echo "info1: probably db ($DB_NAME) doesn't exist"
+        echo "info2: probably db_user ($DB_USER) doesn't exist"
+        echo "info3: probably db_password ($DB_PASS) is wrong"
+        create_db_if_not_exist $DB_NAME
+        create_db_user_if_not_exist $DB_NAME $DB_USER $DB_PASS
+    else
+        if [ $table_count -gt 0 ];then
+            echo "  [ ERROR ] [ ${LINENO} ] DB is not empty ( $DB_NAME ) ( table_count : $table_count ), truncate database before restore"
+            echo
+            echo "  Help: Truncate Database"
+            echo
+            echo "  ./truncate_db '$DB_HOST' '$DB_PORT' '$DB_NAME' '$DB_USER' '$DB_PASS'"
+            echo
+            exit 1
+        fi
     fi
 
 }
 
 function db_empty_check()
 {
-	if [ -n $DB1_NAME ]; then
+	if [ ! -z $DB1_NAME ]; then
 	    is_db_empty  $DB1_NAME $DB1_USERNAME  $DB1_PASSWORD 
 	fi
 
-	if [ -n $DB2_NAME ]; then
+	if [ ! -z $DB2_NAME ]; then
 	    is_db_empty  $DB2_NAME $DB2_USERNAME  $DB2_PASSWORD 
 	fi
 
-	if [ -n $DB3_NAME ]; then
+	if [ ! -z $DB3_NAME ]; then
 	    is_db_empty  $DB3_NAME $DB3_USERNAME  $DB3_PASSWORD 
 	fi
 
-	if [ -n $DB4_NAME ]; then
+	if [ ! -z $DB4_NAME ]; then
 	    is_db_empty  $DB4_NAME $DB4_USERNAME  $DB4_PASSWORD 
 	fi
 }
 
+function create_website_root_if_not_exist(){
+    mkdir -p ${WEBSITE_ROOT_DIR} 2> /dev/null 1> /dev/null
+}
+
 function dir_empty_check()
 {
+
     file_count=`ls ${WEBSITE_ROOT_DIR}/ | wc -l`
     if [ $file_count -gt 0 ];then
-        echo "  [ ERROR ] [ ${LINENO} ] website root directory is not empty, clear all files before restoring"
+        echo "  [ ERROR ] [ ${LINENO} ] website root directory ( $WEBSITE_ROOT_DIR ) is not empty, clear all files before restoring"
         echo
-        echo "      -> $WEBSITE_ROOT_DIR"
+        echo "  Help: Clear all files from website root"
         echo
+        echo "  rm -rf $WEBSITE_ROOT_DIR/*"
         echo
+
         exit 1
     fi
 }
@@ -72,16 +130,16 @@ function dir_empty_check()
 function config_mismatch_check(){
     OLD=$1
     NEW=$2
-    if [ "$OLD" = "$NEW" ]; then
-	echo "[ WARNING ] manually search and replace the following string,"
+    if [ "$OLD" != "$NEW" ]; then
+	echo "  [ WARNING ] manually search and replace the following string,"
         echo
 	echo "    [ $OLD -> $NEW ]"
         echo
-        echo "Location to change: "
+        echo "    Location to change: "
         echo "    "
-        echo "    -> $SOURCE_PATH/db"
-        echo "    -> $SOURCE_PATH/code"
-        echo "    -> $CURRENT_DIR/.config_old.sh"
+        echo "        -> $SOURCE_PATH/db"
+        echo "        -> $SOURCE_PATH/code"
+        echo "        -> $CURRENT_DIR/.config_old.sh"
         echo "    "
 	config_mismatch=1
     fi
@@ -145,6 +203,12 @@ function import_config()
         echo "  [ ERROR ] Restore Failed, config file missing ( $CURRENT_DIR/config.sh )"
         exit 1
     fi
+
+    LOG_FILE="/tmp/backup.${DOMAIN}.log"
+    echo
+    echo "  Log File : $LOG_FILE"
+    echo
+
 
     verify_config
 
@@ -237,8 +301,8 @@ function print_config()
     [ ! -z $DB3_USERNAME ] && 	{ echo "  DB USERNAME      (3) : $DB3_USERNAME"; }
     [ ! -z $DB4_USERNAME ] && 	{ echo "  DB USERNAME      (4) : $DB4_USERNAME"; }
      
-    echo "  Backup Label      : $BACKUP_LABEL"
-    echo "  Backup File       : ${BACKUP_LABEL}.tar.gz"
+    #echo "  Backup Label      : $BACKUP_LABEL"
+    #echo "  Backup File       : ${BACKUP_LABEL}.tar.gz"
     echo 
 }
 
@@ -255,12 +319,21 @@ function import_db(){
 	DB_USER=$2
 	DB_PASS=$3
 	DB_DUMP=$4
-	
+    cd $SOURCE_PATH
+
+    ls $DB_DUMP 2>/dev/null 1>/dev/null
+
+    if [ $? -ne 0 ]; then
+        echo "    error: DB dump file missing ($SOURCE_PATH/$DB_DUMP )"
+        exit 1
+    fi
+
+
 	if [[ -z $MYSQL_ADMIN_USERNAME ]]; then
-		mysql -u$DB_USER  -p$DB_PASS $DB_NAME < $DB_DUMP
+		mysql -u$DB_USER  -p$DB_PASS -h $DB_HOST  -P $DB_PORT $DB_NAME < $DB_DUMP 2>/dev/null 1>/dev/null
 		[ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] Database Import Failed ( DB_NAME : $DB_NAME) "; exit 1; }
 	else
-		mysql -u$MYSQL_ADMIN_USERNAME  -p$MYSQL_ADMIN_PASSWORD $DB_NAME < $DB_DUMP
+		mysql -u$MYSQL_ADMIN_USERNAME  -p$MYSQL_ADMIN_PASSWORD -h $DB_HOST -P $DB_PORT $DB_NAME < $DB_DUMP 2>/dev/null 1>/dev/null
 		[ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] Database Import Failed ( DB_NAME : $DB_NAME) "; exit 1; }
 	fi
 
@@ -271,19 +344,19 @@ function importe_database()
 {
     cd $SOURCE_PATH
 
-    if [ -n $DB1_NAME ]; then
+    if [ ! -z $DB1_NAME ]; then
     import_db $DB1_NAME $DB1_USERNAME $DB1_PASSWORD "db/${DB1_NAME}.sql"
     fi
 
-    if [ -n $DB2_NAME ]; then
+    if [ ! -z $DB2_NAME ]; then
     import_db $DB2_NAME $DB2_USERNAME $DB2_PASSWORD "db/${DB2_NAME}.sql"
     fi
     
-    if [ -n $DB3_NAME ]; then
+    if [ ! -z $DB3_NAME ]; then
     import_db $DB3_NAME $DB3_USERNAME $DB3_PASSWORD "db/${DB3_NAME}.sql"
     fi    
     
-    if [ -n $DB4_NAME ]; then
+    if [ ! -z $DB4_NAME ]; then
     import_db $DB4_NAME $DB4_USERNAME $DB4_PASSWORD "db/${DB4_NAME}.sql"
     fi
 }
@@ -292,8 +365,24 @@ function importe_code()
 {
     cd $SOURCE_PATH
 
-    cp -arf code/. ${WEBSITE_ROOT_DIR}/
-    [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] Website copy failed"; exit 1; }
+    cp -arf code/. ${WEBSITE_ROOT_DIR}/ 2>/dev/null 1>/dev/null
+    if [ $? -ne 0 ]; then
+        #some system doesn't support -a option
+        cp -rf code/. ${WEBSITE_ROOT_DIR}/
+        [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] Website copy failed"; exit 1; }
+        cp -rf code/.htaccess ${WEBSITE_ROOT_DIR}/
+        cp -rf code/.* ${WEBSITE_ROOT_DIR}/
+    fi
+}
+
+function update_backupNrestore_tool(){
+    cd $SOURCE_PATH
+    cp -arf $TOOL_NAME ${WEBSITE_ROOT_DIR}/ 2>/dev/null 1>/dev/null
+    if [ $? -ne 0 ]; then
+        #some system doesn't support -a option
+        cp -rf $TOOL_NAME ${WEBSITE_ROOT_DIR}/
+        [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] ( $TOOL_NAME ) copy failed"; exit 1; }
+    fi
 }
 
 function verify_dns_config()
@@ -303,7 +392,7 @@ function verify_dns_config()
 
     if [ $? -ne 0 ]; then
 	echo 
-	echo "[ WARNING! ] Domain name ( $DOMAIN ) is not pointing to this server, fix DNS config or nginx configuration"
+	echo "  [ WARNING! ] Probably domain name ( $DOMAIN ) is not pointing to this server, fix DNS config or nginx configuration"
 	echo
 	verify_error=1
     fi
@@ -323,6 +412,9 @@ function verify_restore()
     echo
 }
 
+function configure_ownership(){
+    chown www-data:www-data ${WEBSITE_ROOT_DIR} -R 2>/dev/null 1>/dev/null
+}
 
 function main()
 {
@@ -334,10 +426,13 @@ function main()
     remove_trailing_slash
     print_config
     get_abs_path_website_root
-    db_empty_check
+    create_website_root_if_not_exist
     dir_empty_check
+    db_empty_check
     importe_database
     importe_code
+    update_backupNrestore_tool
+    configure_ownership
     verify_restore
 }
 
